### PR TITLE
Add support for devices with multiple outlets

### PR DESCRIPTION
**Pull request by dhylands**

### CODE REVIEW

**Comment by benfrancis** [comment]
Just out of interest, how does this get exposed on the API and UI?

**Comment by dhylands** [comment]
The first on/off control is given type OnOffProperty and the 2nd and subsequent ones are given BooleanProperty (so they're just check boxes).

**Comment by mrstegeman** [comment]
Does this still need to be merged, or is it no longer necessary?

**Comment by dhylands** [comment]
I ordered a device with multiple outputs to test and it hasn't arrived yet. As soon as it arrives, I'll test things and merge.

**Comment by mrstegeman** [comment]
@dhylands did you ever get around to testing this?

**Comment by davehylands** [comment]
No. Although I think I still have the device in question, so I'll see if I can give it a test.

**Comment by mrstegeman** [comment]
Replaced by #240

**Pull request closed without merging**
